### ISSUE TITLE
Should we require @dtd-version?

### ISSUE THREAD

**Issue by Klortho** [JATS4R/JATS4R-Participant-Hub#113]
See http://jatspan.org/niso/publishing-1.1d3/#p=attr-dtd-version.

This attribute is defined as "FIXED", which means: 

* The attribute is optional -- it doesn't have to be present in an instance document
* If it is present, its value *must* be the exact same as that specified in the DTD, e.g. "1.1d3".

It's a nice attribute, because it enables consumers (bots) to determine the version of the schema that the document conforms to, without having to read the doctype declaration or any processing instructions. OTOH, making this attribute required by JATS4R would put an extra burden on the content providers. Then again, it's best practice, and I'd guess that most of them are doing it anyway.

**Comment by jats-laura** [comment]
>I'd guess that most of them are doing it anyway

I don't think they are, actually. PMC gets very little data with the attribute explicitly stated.

**Comment by hubgit** [comment]
Presumably the intention is that the value is read from the DTD rather than the XML file, so there's no reason to add it to the XML.

However, if we're encouraging re-use in environments that don't use the DTD, it might make sense to require it. It would have to be accurate, though…

**Comment by Klortho** [comment]
I think it's a good best practice. What if we made it a warning if the attribute is not present?

**Comment by Klortho** [comment]
It came up in the call just now, that we can use @dtd-version in the Schematron, to determine which license rules to apply (see #50). That would simplify things quite a bit for us. And using the test that "what's good for us is good for reuse", suggests that we should require it.

**Comment by ahamelers** [comment]
There seemed to be widespread support to require it on the call. Can anyone
think of any compelling reason not to require it?

**Comment by Klortho** [comment]
This is a warning if it is not there.
