### ISSUE TITLE
Image table as  good as tag table, using "alternatives" tag and CSV standard file

### ISSUE THREAD

**Issue by ppKrauss** [JATS4R/JATS4R-Participant-Hub#117]
Tabular data have a lot of little problems, about "imperfect conversion" or "visual vs usable" decisions...

The main advantage of a _XML-table_ (`table-wrap` with `table` tag) over _image table_ (`table-wrap` with `graphic` tag), is that the first can be copy/pasted to a data sheet... So, the image is not a [open data](https://en.wikipedia.org/wiki/Open_data), the XML is open. In a scientific context, the advantage of open data is [reproducibility](https://en.wikipedia.org/wiki/Reproducibility)... 

Today there are [standards for CSV](http://dataprotocols.org/tabular-data-package/index.html), of OKFN and [W3C](http://www.w3.org/TR/tabular-data-model/)...

The pair _image+CSV_ (into a [alternatives](http://jats.nlm.nih.gov/publishing/tag-library/1.1d3/element/alternatives.html) tag), the "image of table" file and the CSV file, have all advantages, so is as good as   _table tag_. 

---

When good  _table tag_ is not possible, this _image+CSV_  can be a JATS4R recommendation.
### Example

``` xml
<table-wrap id="pbio-0020328-t003" position="float">
 <label>Table 3</label>
 <caption>
   <title>Systematic Inactivation of SpoIIID-Activated Genes</title>
 </caption>
 <alternatives>
   <graphic xlink:href="pbio.0020328.t003.tif"/>
   <media mime-subtype="csv" mimetype="text" position="anchor" 
     specific-use="processable-format" 
     xlink:href="pbio.0020328.t003.csv"/>
 </alternatives>
</table-wrap>
```

**Comment by ppKrauss** [comment]
Hi @Melissa37, this old post was about an [Open Science](https://en.wikipedia.org/wiki/Open_science) demand...  It is perhaps out of context here (?),  or  the `<table-wrap>` of example is [invalid](http://jats4r.org/validator/) (?)... Can you explain something about the "close issue"?

**Comment by Melissa37** [comment]
Hi @ppKrauss I am sorry about that, I was trying to clean up the Github issues area as there has been a move away from GitHub for the group. I have re-opened it and added to a googledoc the team are using!
I hope you saw the recent issue I opened aimed at people like you who are watching this repo. I don't want for us to lose your valuable input.

Thanks!
Melissa
