### ISSUE TITLE
Best practices: ORCID IDs

### ISSUE THREAD

**Issue by pkra** [JATS4R/JATS4R-Participant-Hub#119]
I was hoping to tap into the community knowledge. 

For a project with a mathematical publisher, we've used something like 

``` xml
<contrib-group content-type="authors">
        <contrib contrib-type="author">
          <contrib-id contrib-id-type="orcid">http://orcid.org/0000-zzz-yyy-xxx</contrib-id>
          <name name-style="western">
            <surname>John</surname>
            <given-names>Doe</given-names>
          </name>
          <aff>Doe's Institute of Advanced JATS</aff>
          <email>john@doe.math</email>
        </contrib>
...
</contrib-group>
```

I've also seen just `<uri content-type="orcid" xlink:href="http://orcid.org/0000-0002-7361-560X"/>` in the wild and I'm wondering what people here consider best practice.

**Comment by hubgit** [comment]
There's [an example of using `orcid` as a `contrib-id-type` value in the JATS documentation](http://jatspan.org/niso/publishing-1.0/#p=elem-contrib-id), so I'd say that's best practice.

**Comment by pkra** [comment]
Right, sorry, I should've linked to that. Still, seeing other examples in the wild made us wonder.
