### ISSUE TITLE
What about articles that have licenses that change over time?

### ISSUE THREAD

**Issue by Klortho** [JATS4R/JATS4R-Participant-Hub#14]
Should we address this case?

**Comment by Melissa37** [comment]
Can someone add an example here?

**Comment by jeffbeckncbi** [comment]
http://tinyurl.com/q2w9aj4

Jeff

**Comment by Melissa37** [comment]
Ah, sorry, now I understand - it's referring to embargo time periods

**Comment by pdonohoe** [comment]
The NISO Recommendation is to add a date attribute to the <license_ref> element, to indicate the starting date of each license; no end date is required.  We could do the same, adding attribute iso-8601-date to <license>, which would also fulfil our requirement for machine-readability. <license> is already repeatable within <permissions>.
