### ISSUE TITLE
<caption> <label> <title>

### ISSUE THREAD

**Issue by Daniel-Mietchen** [JATS4R/JATS4R-Participant-Hub#19]
In
http://eutils.ncbi.nlm.nih.gov/entrez/eutils/efetch.fcgi?db=pmc&id=PMC2910478 ,
`<caption>` tags are used in a rather strange way. `<label>` and `<title>` tags are not used.

As mentioned in the call, I am not sure how to move forward with this one, but I would like to have a recommendation of the sort that there should always be one `<label>`, one `<caption>` and one `<title>` tag _per file_ (or table), perhaps with some concrete statements as to what should go in there, and where.

**Comment by Melissa37** [comment]
Figure and table example files are in elements:

https://github.com/JATS4R/elements/blob/master/figure.md

https://github.com/JATS4R/elements/blob/master/table.md

Please add further examples so we can take a look at what people are doing and what the JATS4R recommendation should be.

**Comment by Melissa37** [comment]
Also boxes example file created, please add examples:

https://github.com/JATS4R/elements/blob/master/boxes.md
