### ISSUE TITLE
Sub-article keywords

### ISSUE THREAD

**Issue by Daniel-Mietchen** [JATS4R/JATS4R-Participant-Hub#21]
For things like tables, equations or figures, it would be very useful to have dedicated keywords that facilitate discovery and reuse of these items.

**Comment by Melissa37** [comment]
eLife agrees that this would be nice; however it would involve a large amount of work for authors and publishers.

**Comment by Klortho** [comment]
I think it is out of scope for this group to *define* such a list.  But, for list(s) that are published and controlled, we could look at how to reference them in a machine-readable way.

For example, for MeSH, maybe something like:

```xml
<kwd-group kwd-group-type="MeSH-2014">
  <kwd>Calcimicyn</kwd>
  <kwd>Oflaxacin</kwd>
  ...
</kwd-group>
```

Then, we'd want to control the list of values allowed in the `kwd-group-type` attribute.
