### ISSUE TITLE
Data citation

### ISSUE THREAD

**Issue by Daniel-Mietchen** [JATS4R/JATS4R-Participant-Hub#30]
Now that data citation is en route to become available in JATS and thus for machines, I think it would be good to take a JATS4R perspective on it and come up with some tagging recommendations, so that we can give the harvesting of data citations a cleaner start than other forms of reuse of JATS.

**Comment by Melissa37** [comment]
I am just preparing a sample for testing on our host's display.
Before going through that process, I wanted to include what I have for analysis by the group.
Currently we call out Data citations in a separate section of the article. I plan to carry on doing so, but will also add them to the reference list.

This will be the reference entry:
`<ref id="bib46">
                <element-citation publication-type="data">
                    <person-group person-group-type="author">
                        <name><surname>Ly</surname>
                            <given-names>T</given-names></name>,
                        <name><surname>Endo</surname>
                            <given-names>A</given-names></name>,
                        <name>
                            <surname>Lamond</surname><given-names>Angus
                                I</given-names></name></person-group>
                        <year>2014</year>
                        <source>Proteomics dataset</source>
                        <ext-link ext-link-type="uri" xlink:href="http://proteomecentral.proteomexchange.org"
                            >http://proteomecentral.proteomexchange.org</ext-link> 
                </element-citation>
            </ref>`

And this is how we will mark it in the Data citation section (the bib call out is subject to change):
`<sec sec-type="datasets">
                <title>Major dataset</title>
                <p>The following dataset was generated:<xref
                    ref-type="bibr" rid="bib46"/></p>
                <p>
                    <related-object content-type="generated-dataset" id="dataro1"
                                ><name><surname>Ly</surname><given-names>T</given-names></name>,
                                <name><surname>Endo</surname><given-names>A</given-names></name>,
                                <name><surname>Lamond</surname><given-names>Angus
                            I</given-names></name>, <year>2014</year><x>, </x><source>Proteomics
                            dataset</source><x>, </x><object-id pub-id-type="art-access-id"
                            >PXD001610</object-id><x>; </x><ext-link ext-link-type="uri"
                            xlink:href="http://proteomecentral.proteomexchange.org"
                            >http://proteomecentral.proteomexchange.org</ext-link><x>,
                            </x><comment>ProteomeXchange Consortium.</comment></related-object>
                </p>
            </sec>`

Any input welcome!

**Comment by Melissa37** [comment]
I have found another variation on this:

`<ref id="bib46">
                <element-citation publication-type="web">
                    <person-group person-group-type="author">
                        <name>
                            <surname>Schuman</surname>
                            <given-names>M</given-names>
                        </name>
                        <name>
                            <surname>Barthel</surname>
                            <given-names>K</given-names>
                        </name>
                        <name>
                            <surname>Baldwin</surname>
                            <given-names>IT</given-names>
                        </name>
                    </person-group>
                    <year>2012</year>
                    <comment>Data from: Herbivory-induced volatiles function as defenses increasing
                        fitness of the native plant <italic>Nicotiana attenuata</italic> in nature.
                        Dryad Digital Repository.</comment>
                    <ext-link ext-link-type="uri" xlink:href="http://dx.doi.org/10.5061/dryad.gs45f"
                        >http://dx.doi.org/10.5061/dryad.gs45f</ext-link>
                </element-citation>
            </ref>'
It has proven a bit difficult for us because it does not have a title or a source, just a comment. This is a collection of datasets in Dryad. Maybe each data file should be a new reference?

**Comment by Melissa37** [comment]
Examples on JATS:

http://jats.nlm.nih.gov/archiving/tag-library/1.1d2/chapter/tag-cite-archving-e5.html#arc-tag-cite-archving-e5

**Comment by Klortho** [comment]
See [minutes from 7/23/2015 meeting for some notes/decisions](https://docs.google.com/document/d/1ZvUMuE09QqtzRnt3Y-10dAcE2PeZl02N3nJGlQb7ty0/edit#).

We need to start drafting recommendations on the wiki, [here](https://github.com/JATS4R/elements/wiki/references-citations).

**Comment by Klortho** [comment]
I still have some concerns that perhaps we should add some more examples to the [data citations draft](https://docs.google.com/document/d/13uGZ4UqplHkT9VvaXnuboLZ2IRCx3SH7PTQJk24CiRk/edit).

Here are some sources for examples:

* [JATS Tag library](http://jats.nlm.nih.gov/archiving/tag-library/1.1d2/chapter/tag-cite-archving-e5.html#arc-tag-cite-archving-e5)
* Our own [references-citations.md file](https://github.com/JATS4R/JATS4R-Participant-Hub/blob/master/examples/references-citations.md).
