### ISSUE TITLE
Distinguishing references with a,b,c

### ISSUE THREAD

**Issue by Melissa37** [JATS4R/JATS4R-Participant-Hub#37]
Where a paper cites articles where the authors and the year are the same, most publishers add a,b,c etc to the reference year to allow distinguishing the references.

It's only use is for the reference in this one context, being cited in this particular article. It is not part of the reference. 

How should we recommend publishers deal with this?

We've been adding it to the year, `<year>2014a</year>`

I think this is wrong.

**Comment by hubgit** [comment]
Always adding an `iso-8601-date` attribute containing just the year is a good solution:
```xml
<year iso-8601-date="2007">2007b</year>
```

See [a related jats-list discussion](http://www.biglist.com/lists/lists.mulberrytech.com/jats-list/archives/201302/msg00028.html).

**Comment by Melissa37** [comment]
Nice
