### ISSUE TITLE
<alternatives> (and math)

### ISSUE THREAD

**Issue by pkra** [JATS4R/JATS4R-Participant-Hub#54]
I recently was surprised that

``` xml
<inline-formula>
    <alternatives>
        <textual-form>5:1</textual-form>
    </alternatives>
    <mml:math display="inline">
        <mml:mrow>
            <mml:mn mathvariant="normal">5</mml:mn>
            <mml:mo>:</mml:mo>
            <mml:mn mathvariant="normal">1</mml:mn>
        </mml:mrow>
    </mml:math>
</inline-formula>
```

seems to be valid. My question is:

**If `<alternatives>` is used (within `<*-formula>` or elsewhere), should the recommendation be that `<alternatives>` should be the only child?**

We had the discussion about identifying preferred alternatives on the calls regarding math and the decision was that there shouldn't be a preferred alternative. This kind of markup is a round-about way to still mark a preferred version.

(The current recommendation at http://jats4r.org/recommendations/math.html doesn't say much about this.)

**Comment by pkra** [comment]
Moreover, it adds to the pain of looking up alternative formats.

**Comment by Klortho** [comment]
I agree that this markup should be an error.  Right now, our validator doesn't complain about it.

Here's a complete document, for convenience in testing:

```xml
<?xml version="1.0" encoding="UTF-8"?>

<article dtd-version="1.0"  xmlns:mml='http://www.w3.org/1998/Math/MathML'>
  <front>
    <journal-meta>
      <journal-id></journal-id>
      <issn></issn>
    </journal-meta>
    <article-meta>
      <title-group>
        <article-title>Archival DTD Test Article</article-title>
        <subtitle>(Just a small one for parsing)</subtitle>
      </title-group>
      <pub-date>
        <year>2015</year>
      </pub-date>
    </article-meta>
  </front>
  <body>

<inline-formula>
    <alternatives>
        <textual-form>5:1</textual-form>
    </alternatives>
    <mml:math display="inline">
        <mml:mrow>
            <mml:mn mathvariant="normal">5</mml:mn>
            <mml:mo>:</mml:mo>
            <mml:mn mathvariant="normal">1</mml:mn>
        </mml:mrow>
    </mml:math>
</inline-formula>

  </body>
</article>
```

**Comment by pkra** [comment]
Thanks, @Klortho!

**Comment by jats-laura** [comment]
I think saying that if &lt;alternatives> exists in &lt;&#42;-formula&gt;, it can be the only child is far too limiting. I agree that the example from @pkra should be an error, but we can't limit both &lt;inline-formula> and &lt;disp-formula> in the same way.

I think the rule for &lt;disp-formula> needs to be really clear that if &lt;alternatives> is used, no other math can be used outside it, but we can't prevent people from using things like &lt;label> in &lt;disp-formula>.

**Comment by pkra** [comment]
@jats-laura thank you! I had not thought of `<label>`. Is there a short list of similar elements?

Also, how should something be said to reconcile `<label>` with the recommendations to use MathML and LaTeX? Both have standardized labeling constructs and I would expect them to carry the label already (because it's tricky to inject a label later). The recommendation might want to say that the should all be identical :-). But I don't know what kind of crazy stuff can be found in the wild here. (I have to admit I would never use `<label>` on math :-( .)

**Comment by jats-laura** [comment]
Not short lists, but the Tag Library has lists:
* http://jats.nlm.nih.gov/archiving/tag-library/1.1d3/element/disp-formula.html
* http://jats.nlm.nih.gov/archiving/tag-library/1.1d3/element/inline-formula.html
I'd say at a bare minimum, we'd have to allow &lt;label> as well as the accessibility elements &lt;alt-text> and &lt;long-desc>. I'm not sure that's enough, though.

At this point I'm thinking maybe a slightly different approach: If &lt;alternatives> exists in &lt;*-formula> then none of the elements allowed in &lt;alternatives> can be a sibling. 
http://jats.nlm.nih.gov/archiving/tag-library/1.1d3/element/alternatives.html
So it would restrict these elements from being tagged as siblings of &lt;alternatives>:
<code>&lt;array></code>, <code>&lt;chem-struct></code>, <code>&lt;code></code>, <code>&lt;graphic></code>, <code>&lt;inline-graphic></code>, <code>&lt;private-char></code>, <code>&lt;inline-supplementary-material></code>, <code>&lt;media></code>, <code>&lt;preformat></code>, <code>&lt;supplementary-material></code>, <code>&lt;table></code>, <code>&lt;tex-math></code>, <code>&lt;mml:math></code>

The &lt;textual-form> element is only allowed in &lt;alternatives>, so the slightly tricky part of that is someone *could* conceivably tag the math in plain text outside of the &lt;alternatives>. Maybe in that case it would be enough to issue a warning if plain text or the emphasis elements appeared outside the &lt;alternatives; in a formula?

**Comment by Klortho** [comment]
I like that approach.
+1

**Comment by pkra** [comment]
I admit I'm slightly confused why `<alt-text>` and `<longdesc>` are not considered alternatives. But no objections since my experience with JATS-in-the-wild is far too limited to judge.

**Comment by jats-laura** [comment]
I think the quick answer is that they're accessibility elements and not processing alternatives which is the core of the &lt;alternatives> definition. 

If I remember correctly, the idea behind &lt;alternatives is that each object in it could substitute for the others so systems could pick one. I know that's how PMC does it. But that same limitation, of just picking one, shouldn't be applied to the accessibility elements. They should always be available, regardless of which object format is displayed.
