### ISSUE TITLE
Contributions - please upload your samples

### ISSUE THREAD

**Issue by Melissa37** [JATS4R/JATS4R-Participant-Hub#58]
Need samples of how different publishers tag this content so we can see the variety and recommend some standards

**Comment by hubgit** [comment]
I've created [an "author contributions" file](https://github.com/JATS4R/elements/blob/master/contributions.md) and added a PeerJ example. 

We're not using any standard ontology at the moment, but I like the [CASRAI Contributor Roles](http://dictionary.casrai.org/Contributor_Roles) (apart from the URLs).

**Comment by hubgit** [comment]
Related: [PLOS Author Contributions](http://hack4ac.com/plos-author-contributions/) - a project from the Hack4Ac hack day that mined author contributions from PLOS (and PeerJ) articles.

**Comment by Melissa37** [comment]
Have added eLife examples
