### ISSUE TITLE
Should we submit a paper to COASP?

### ISSUE THREAD

**Issue by Melissa37** [JATS4R/JATS4R-Participant-Hub#63]
Is anyone from the group attending the annual conference?

http://oaspa.org/call-for-contributions-to-the-7th-coasp/

Now established as a key event in the scholarly publishing calendar, the conference is directed towards the interests of professional publishing organisations, independent publishers and university presses, librarians, university administrators, funding organisations, policy makers and other stakeholders. Participants will have the opportunity to hear from many leading figures within the open access publishing environment and to discuss recent developments, innovations and best practices within the industry.

The Program Committee have set aside one of the sessions within the conference program as a Show & Tell opportunity for showcasing exciting new products, projects, ideas or initiatives relating to open access publishing as this proved to be such a success last year. Six slots are available and organisations are invited to submit a proposal to us for a 10 minute presentation.

All proposals should be submitted by 31 May 2015 at the latest to info@oaspa.org.  The Program Committee will then review the suggestions and make a final decision by the end of June.  If you aren’t selected for a Show and Tell then there may be an opportunity for you to present a poster on your topic at the conference.

Please note that while we will be able to cover the registration costs for the authors of successful proposals, we are not able to cover any of the travel expenses that may be incurred in attending the conference.

Further announcements will be made shortly when registrations for the event are open and the preliminary program is available.

**Comment by Klortho** [comment]
I think it would be a great opportunity to increase awareness of our group.  I doubt I'd be able to go, but I could help prepare a proposal.

**Comment by Melissa37** [comment]
Hi there
If no other members of JATS4R are attending I could probably go, but would prefer not! However, I think it's important we do get the word out and do this.

M

**Comment by kaveh1000** [comment]
I am happy to do it if they don't mind me giving my own talk and also on
behalf of Jats4reuse (with no guarantee of either accepted). So you could
submit on behalf of Jats4r without specifying a speaker, saying there will
be a speaker on our behalf but not decided yet. How is that?

On 9 May 2015 at 20:18, Melissa Harrison <notifications@github.com> wrote:

> Hi there
> If no other members of JATS4R are attending I could probably go, but would
> prefer not! However, I think it's important we do get the word out and do
> this.
>
> M
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JATS4R/elements/issues/63#issuecomment-100533188>.
>



-- 
Kaveh Bazargan
Director
River Valley Technologies
@kaveh1000
+44 7771 824 111
kaveh@rivervalleytechnologies.com
www.rivervalleytechnologies.com

**Comment by Melissa37** [comment]
Good-oh. Thanks M

**Comment by Klortho** [comment]
We decided yesterday that we'll submit an abstract for one of the 10-minute sessions:

* Melissa will draft something on Google docs by Wednesday, 20th.
* Gather comments until 27th.
* Abstract due on the 30th.

**Comment by Melissa37** [comment]
We've been accepted!

The message is below. 
Kaveh, I might attend and so could present, but as yet undecided. I responded to that effect asking when they need to know by and said you would present if I did not. Hope that's OK?

Dear Melissa,

I apologise for being a few days late to get back to you regarding the proposal you sent for a Show and Tell presentation at COASP in Amsterdam.  We received a lot of excellent suggestions - more than we anticipated - and it has taken longer than expected to review them all thoroughly and make a selection.

I am pleased to be able to tell you that your presentation has been chosen to fill one of the six slots.  You should aim for your talk to be a maximum of 8 minutes and we will allow for a couple of minutes of questions.

This year we are waiving the registration fees for all speakers so if you could please confirm to me that you are still able to join us at the conference then I can add your name to the list of attendees.

I look forward to hearing from you and do let me know if you have any questions.

With kind regards,
Claire

**Comment by kaveh1000** [comment]
Sure. Sounds good, Melissa..

On 3 July 2015 at 12:34, Melissa Harrison <notifications@github.com> wrote:

> We've been accepted!
>
> The message is below.
> Kaveh, I might attend and so could present, but as yet undecided. I
> responded to that effect asking when they need to know by and said you
> would present if I did not. Hope that's OK?
>
> Dear Melissa,
>
> I apologise for being a few days late to get back to you regarding the
> proposal you sent for a Show and Tell presentation at COASP in Amsterdam.
> We received a lot of excellent suggestions - more than we anticipated - and
> it has taken longer than expected to review them all thoroughly and make a
> selection.
>
> I am pleased to be able to tell you that your presentation has been chosen
> to fill one of the six slots. You should aim for your talk to be a maximum
> of 8 minutes and we will allow for a couple of minutes of questions.
>
> This year we are waiving the registration fees for all speakers so if you
> could please confirm to me that you are still able to join us at the
> conference then I can add your name to the list of attendees.
>
> I look forward to hearing from you and do let me know if you have any
> questions.
>
> With kind regards,
> Claire
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JATS4R/elements/issues/63#issuecomment-118322985>.
>



-- 
Kaveh Bazargan
Director
River Valley Technologies
@kaveh1000
+44 7771 824 111
www.rivervalleytechnologies.com
www.bazargan.org
