### ISSUE TITLE
Persuade databases to use Journals' own IDs/ensure consistent abbreviation/capitalisation

### ISSUE THREAD

**Issue by Melissa37** [JATS4R/JATS4R-Participant-Hub#75]
May be beyond the remit of JATS4R, but would be good if all the journal-ids were identical, irrespective of the journal-id-type?

eg:
`<journal-id journal-id-type="nlm-ta">elife</journal-id>
<journal-id journal-id-type="hwp">eLife</journal-id>
<journal-id journal-id-type="publisher-id">eLife</journal-id>`

eLife has a capital L but lower case e, is changed for NLM database.

**Comment by jats-laura** [comment]
I think the important part is that the abbreviations be correct to the referenced authority, something which I believe is outside of the scope of JATS4R. If the abbreviations were all identical (an ideal situation, to be sure), the element wouldn't need to repeat.

Incidentally, the NLM-TA for eLife is actually "Elife": http://www.ncbi.nlm.nih.gov/nlmcatalog/?term=elife[journal]

**Comment by Melissa37** [comment]
Ah, ha, so what we're providing is not even right! I'll correct that in our deliveries :-)

It's a good point that it's really outside of the scope of JATS4R, however, it has implications on reusability so we should be campaigning for it if we can, I think.
