### ISSUE TITLE
Dates recorded - please provide samples

### ISSUE THREAD

**Issue by Melissa37** [JATS4R/JATS4R-Participant-Hub#76]
https://github.com/JATS4R/elements/blob/master/dates.md

**Comment by jats-laura** [comment]
I noticed that the eLife date example includes a a collection date with the pub-type attribute:
```xml
            <pub-date pub-type="collection">
                <year>2014</year>
            </pub-date>
```
That attribute is officially deprecated as of 1.1d1:
http://jats.nlm.nih.gov/archiving/tag-library/1.1d3/attribute/pub-type.html

PMC's recommendation for tagging this date is now by using @publication-format="electronic" and @date-type="collection":
http://www.ncbi.nlm.nih.gov/pmc/pmcdoc/tagging-guidelines/article/tags.html#el-pubdate
(example for v1.0 in the blue box)

I think we should probably stay away from anything that's deprecated.
