### ISSUE TITLE
Interactive figures

### ISSUE THREAD

**Issue by Melissa37** [JATS4R/JATS4R-Participant-Hub#95]
Hi there

Has anyone got any recommendations on how to tag these? We've not published any yet on our site, but wondered whether there is best practice

**Comment by hubgit** [comment]
I think it depends on whether the interactive figure is a supplement to the main figure, or an alternative rendering of the same information.

If it's a supplement then it can be marked up as a supplemental figure (as eLife already does); if it's an alternative rendering then it can be marked up using `<alternatives>`, and the renderer can use the figure image as a clickable preview for the interactive figure. 

This also works for videos and other types of figures that aren't plain images - but still usually requires an image to use as the preview and in static contexts such as PDF.
