### ISSUE TITLE
Citing computer programs

### ISSUE THREAD

**Issue by Melissa37** [JATS4R/JATS4R-Participant-Hub#96]
Hi there

Reviewing our wonky references, have come up with a number of computer programs that have been referenced in weird and wonderful ways, and are pretty hard to track down as a result of that.
Does anyone have an guidance on what they do?

An example from our archive below:

`<ref id="bib70">
                <element-citation publication-type="other">
                    <person-group person-group-type="author">
                        <name>
                            <surname>Swofford</surname>
                            <given-names>DL</given-names>
                        </name>
                    </person-group>
                    <year>2003</year>
                    <comment>PAUP*. Phylogenetic analysis using Parsimony (*and other methods).
                        Version 4 Sinauer Associatesm Sunderland, Massachusetts</comment>
                </element-citation>`

**Comment by hubgit** [comment]
There's a fair amount of discussion of software citation in [this Code as a Research Object thread](https://github.com/mozillascience/code-research-object/issues/12).

An example for [this software](http://cran.r-project.org/web/packages/nlme/citation.html) would be this XML, but it could do with more detail, still (which operating system, etc):

```xml
<element-citation publication-type="software">
  <person-group person-group-type="author">
    <name><surname>Pinheiro</surname><given-names>J</given-names></name>
    <name><surname>Bates</surname><given-names>D</given-names></name>
    <name><surname>DebRoy</surname><given-names>S</given-names></name>
    <name><surname>Sarkar</surname><given-names>D</given-names></name>
    <collab>R Core Team</collab>
  </person-group>
  <source>nlme: linear and nonlinear mixed effects models</source>
  <edition designator="3.1-89">R package version 3.1-89</edition>
  <uri>http://cran.r-project.org/package=nlme</uri>
  <year iso-8601-date="2008">2008</year>
</element-citation>
```

**Comment by hubgit** [comment]
A related JATS-LIST discussion thread: http://www.biglist.com/lists/lists.mulberrytech.com/jats-list/archives/201403/msg00013.html

**Comment by Melissa37** [comment]
Fab, thanks Alf
