### ISSUE TITLE
There are a  "semantic mapping" initiative here?

### ISSUE THREAD

**Issue by ppKrauss** [JATS4R/JATS4R-Participant-Hub#97]
"Semantic mapping" is a old proposal, but never really used with NLM or JATS... A lot of semantic are expressed in the JATS documentation and can be extracted/confirmed with JATS _corpora_ (PMC and other  repositories with an infinitude of samples). I think that "semantic map" can be an enhancement for reuse-community and reuse-software.

The counting-statistics of [LOV database](http://lov.okfn.org/dataset/lov/)  show that there are some [de facto standards](https://en.wikipedia.org/wiki/De_facto_standard) like DCterms and FOAF... And the  [increased use at Web](http://webdatacommons.org/structureddata/) of semantic with _de facto_ standards, like [Schema.org](http://schema.org/), show that perhaps "is time to use semantic"... So, "map JATS elements to semantic (to RDF or other)" is a feasible project, and is a realistic demand **to enhance reuse**.

---

**Example**: the _content_ of an [`<aff>` tag](http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-9220.html)  is the "name of an institution or organization" (documentation), so this content is a http://schema.org/Organization
and, as related [`<contrib>`](http://jats.nlm.nih.gov/publishing/tag-library/1.0/n-xs80.html) contributor ("...with which a contributor is affiliated"), a semantic described by http://schema.org/member

Contributor in general is a http://schema.org/Person  but can be also a http://schema.org/Organization .

PS: many other semantic relations can be expressed using https://www.wikidata.org/wiki/Wikidata
(example [Organization is Q43229](https://www.wikidata.org/wiki/Q43229)).

**Comment by jats-laura** [comment]
Have you looked at the Tag Library indices? Mulberry did a lot of work back with version 3.0 to add this kind of info into them. Not exactly mapping to schema.org/XXX, but they do capture a good amount of semantic info.

**Comment by ppKrauss** [comment]
Thanks @jats-laura (!),  do you have some links or references about this Mulberry "semantic  iniciative"?

**Comment by jats-laura** [comment]
I'm just talking about the indices in the Tag Library. The one in Archiving would be the most comprehensive: http://jats.nlm.nih.gov/archiving/tag-library/1.1d3/alpha-index/alpha-index.html

If you're looking for author, for instance, it's not a JATS tag, but the index will tell you what is:
http://jats.nlm.nih.gov/archiving/tag-library/1.1d3/alpha-index/alpha-a.html
> author
* see &lt;attrib>
* use &lt;contrib>
* see @contrib-type

This info is included throughout the index.

**Comment by ppKrauss** [comment]
Hum... As you say, this is "not exactly mapping"... In my opinion it is a "good clue", but far from [Web Semantic solution](https://en.wikipedia.org/wiki/Semantic_Web#Semantic_Web_solutions) or [Linked data initiative](https://en.wikipedia.org/wiki/Linked_data).

**Comment by hubgit** [comment]
One way of mapping JATS elements/attributes to schema.org types/properties is via an XSL transformation to HTML, e.g. those found in [jats-to-html.xsl](https://github.com/PeerJ/jats-conversion/blob/master/src/data/xsl/jats-to-html.xsl) and [its subcomponents](https://github.com/PeerJ/jats-conversion/tree/master/src/data/xsl/jats-to-html).

**Comment by ppKrauss** [comment]
@hubgit Good (!), yes, I think this is the way... Can I collaborate there with this "mapping objective" in mind?  A **suggestion**:

1. enhance  `jats-to-html.xsl` with more  `itemprop`'s (you add a lot of good ones, need only a little more). Some RFDa ( `itemprop`) can be Schema.org, but some need other ([LOV](http://lov.okfn.org/dataset/lov/) or Wikidata vocabularies).

2. express (in a simple CSV file) the XML JATS semantic of main tags and attributes.  ... Perhaps we can enhance [jats-to-rdf](https://github.com/PeerJ/jats-conversion/blob/master/src/data/xsl/jats-to-rdf.xsl) ... perhaps need a map between RDF decisions and `itemprop` decisions.

**Comment by hubgit** [comment]
> enhance jats-to-html.xsl with more itemprop's

Suggestions for extra appropriate schema.org properties would be appreciated. 

[Here's an example of the current output](https://developers.google.com/structured-data/testing-tool?url=https%253A%252F%252Fpeerj.com%252Farticles%252F182.html) (ignore the errors, mostly - it's just showing that "headline" and "image" were recently changed from "optional" to "required").

**Comment by ppKrauss** [comment]
About "map" in a CSV at Github,  the suggestion is to express  XPath semantics, and discuss (looking for consensus) each decision.

JATS-XPath  | is-a | URL1|WikidataID
--- | --- | ---| ---
`/article/back//ref-list/ref` |	prop|	https://schema.org/citation | &lt;Q1631107
`/article/back//ref-list/ref[element-citation/@publication-type = 'journal']` |	class|	http://schema.org/ScholarlyArticle | &lt;Q191067
`/article/back//ref-list/ref[element-citation/@publication-type = 'book']` |	class|	http://schema.org/Book | =Q571
`//front//article-title` | prop| http://schema.org/name | =Q783521

Example of discussion: in `article-title` the `name` property is vague, the semantic [Q783521](https://www.wikidata.org/wiki/Q783521) is  exact, and with SchemaOrg perhaps http://schema.org/headline  is an alternative (URL2) for `name`.
